# Generated by Django 5.2 on 2025-07-06 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_alter_shippingaddress_shipping_address2_order_and_more"),
        ("store", "0005_profile_old_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
