# Generated by Django 5.2 on 2025-07-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_orderitem_price_orderitem_product_orderitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipped",
            field=models.BooleanField(default=False),
        ),
    ]
