[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmd = "pip install -r requirements.txt"

[phases.build]
cmd = "python manage.py collectstatic --noinput"

[start]
cmd = "python manage.py migrate && gunicorn ecom.wsgi:application --bind 0.0.0.0:$PORT"