[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmd = "pip install -r requirements.txt"

[phases.build]
cmd = "python manage.py collectstatic --noinput"

[start]
cmd = "python manage.py migrate && gunicorn ecom.wsgi:application --bind 0.0.0.0:$PORT"