[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate && gunicorn ecom.wsgi --log-file -"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10